<section class="container field">
            <div>
                <h2>Créer un compte</h2>
            </div>
            
            <?php require_once '_errors.phtml'; ?>
                
            
            <form action="index.php?page=register" method="POST">
                <fieldset>
                    <div>
                        <label for="firstname">Prénom</label>
                        <input type="text" name="firstname" id="firstname" value="<?php if(isset($_POST['firstname'])) { echo htmlspecialchars($_POST['firstname'], ENT_QUOTES); } ?>">
                    </div>
                    
                    <div>
                        <label for="lastname">Nom</label>
                        <input type="text" name="lastname" id="lastname" value="<?php if(isset($_POST['lastname'])) { echo htmlspecialchars($_POST['lastname'], ENT_QUOTES); } ?>">
                    </div>
                    
                    <div>
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email"value="<?php if(isset($_POST['email'])) { echo htmlspecialchars($_POST['email'], ENT_QUOTES); } ?>">
                    </div>
                    
                    <div>
                        <label for="password">Password</label>
                        <input type="password" name="password" id="password" value="<?php if(isset($_POST['password'])) { echo htmlspecialchars($_POST['password'], ENT_QUOTES); } ?>">
                    </div>
                    
                    <div>
                        <label for="birthdate">Date de naissance</label>
                        <input type="date" name="birthdate" id="birthdate" value="<?php if(isset($_POST['birthdate'])) { echo htmlspecialchars($_POST['birthdate'], ENT_QUOTES); } ?>">
                    </div>
                    
                    <div>
                        <button>S'enregistrer</button>
                    </div>
                </fieldset>
            </form>
            
            <p class="center">Vous avez déjà un compte ? <u><a href="?page=login">Se connecter</a></u></p>
</section>