<section class="container">
    
    <h2>Panneau d'administration</h2>
    
    <p><a href="?page=admin"> Menu administrateur</a> > <a href="?page=admin_items">Liste des produits du site</a> > <span class="current">Ajouter un produit</span></p>
    
    <?php require_once '_errors.phtml'; ?>
    <?php require_once '_valids.phtml'; ?>
    
    <?php if(isset($valids) && count($valids) > 0): ?>
        <a class="button" href="?page=admin_items_add">Ajouter un autre produit</a>
        <a class="button" href="?page=admin">Retour au panel administrateur</a>
    <?php endif; ?>
    
    <form class="add_item" enctype="multipart/form-data" action="index.php?page=admin_items_add" method="POST">
        
        <p class="add_added">Ajout d'un article</p>
        
        <p>Veuillez choisir la visibiliter du produit :</p>
        <div>
            <input type="radio" id="available1" name="available" value="1" checked />
            <label for="available1">Visible</label>
            
            <input type="radio" id="available0" name="available" value="2" />
            <label for="available0">Non visible</label>
        </div>
        
        
        <label for="categorie">Categorie :</label>
        <select class="pl-1" name="categorie" id="categorie">
            <option value="">-Choisir une categorie-</option>
            
            <?php foreach ($categories as $categorie): ?>
                <option value="<?= htmlspecialchars($categorie['id_categorie'], ENT_QUOTES) ?>"
                <?php if($addItem['categorie'] == $categorie['id_categorie']) :?> selected <?php endif; ?>
                ><?= htmlspecialchars($categorie['title'], ENT_QUOTES)?> </option>
            <?php endforeach ?>
                    
        </select>
        
        
        <label for="maker">Marque :</label>
        <select class="pl-1" name="maker" id="maker">
            <option value="">-Choisir une marque-</option>
            
            <?php foreach ($makers as $maker): ?>
                <option value="<?= htmlspecialchars($maker['id_maker'], ENT_QUOTES) ?>"
                <?php if($addItem['maker'] == $maker['id_maker']) :?> selected <?php endif; ?>
                ><?= htmlspecialchars($maker['maker'], ENT_QUOTES)?> </option>
            <?php endforeach ?>
                    
        </select>

    
        <label for="title">Titre :</label>
        <input type="text" name="title" id="title" value="<?php if(isset($addItem['title'])) { echo htmlspecialchars($addItem['title'], ENT_QUOTES); } ?>">


        <label for="description">Description :</label>
        <textarea id="description" name="description" rows="10" cols="50"><?php if(isset($addItem['description'])) { echo htmlspecialchars($addItem['description'], ENT_QUOTES); } ?></textarea>


        <label for="price">Prix :</label>
        <input type="number" name="price" step="0.01" id="price" value="<?php if(isset($addItem['price'])) { echo htmlspecialchars($addItem['price'], ENT_QUOTES); } ?>">


        <label for="quantity">Quantité :</label>
        <input type="number" name="quantity" id="quantity" value="<?php if(isset($addItem['quantity'])) { echo htmlspecialchars($addItem['quantity'], ENT_QUOTES); } ?>">


        <label for="power">Puissance :</label>
        <input type="number" name="power" step="0.1" id="power" value="<?php if(isset($addItem['power'])) { echo htmlspecialchars($addItem['power'], ENT_QUOTES); } ?>">


        <label for="capacity">Capacité :</label>
        <input type="number" name="capacity" step="0.1"id="capacity" value="<?php if(isset($addItem['capacity'])) { echo htmlspecialchars($addItem['capacity'], ENT_QUOTES); } ?>">


        <label for="origin">Origine :</label>
        <input type="text" name="origin" value="France" id="origin" value="<?php if(isset($addItem['origin'])) { echo htmlspecialchars($addItem['origin'], ENT_QUOTES); } ?>">


        <label for="battery">Batterie :</label>
        <input type="text" name="battery" id="battery" value="<?php if(isset($addItem['battery'])) { echo htmlspecialchars($addItem['battery'], ENT_QUOTES); } ?>">


        <label for="picture">Choisissez la photo principal de l'objet :</label>
        <input type="file" id="picture" name="picture" accept="image/png, image/jpeg, image/jpg, image/gif"/>
    
        <label for="caption">Description de la photo principal :</label>
        <textarea id="caption" name="caption" rows="5" cols="30"><?php if(isset($addItem['caption'])) { echo htmlspecialchars($addItem['caption'], ENT_QUOTES); } ?></textarea>


    
        <button>Ajouter</button>
            
    </form>
    
</section>

<script type="text/javascript" src="public/js/adminCategorieAddItems.js"></script>