<section class="container">
    
    <h2>Panneau d'administration</h2>
    
        <article class="menu">
            
            <h3>Bienvenue sur le panneau d'administration de Vapiora !</h3>
            
            <span class="current">Menus</span>
            
            <ul class="unstyled fields">
                <li><a href="?page=home">Accueil</a></li>
                <li><a href="?page=admin_items">Produits</a></li>
                <li><a href="?page=recipse_message">Messages reçus</a></li>
            </ul>
            
        </article>
    
</section>